name: Run Spring Boot's System Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fix docker
        shell: bash
        run: |
          if [ -f /etc/docker/daemon.json ]; then
            sudo jq '.features."containerd-snapshotter" = false' /etc/docker/daemon.json > /tmp/daemon.json
            sudo mv /tmp/daemon.json /etc/docker/daemon.json
            else
            echo '{"features": {"containerd-snapshotter": false}}' | sudo tee /etc/docker/daemon.json
          fi
          sudo systemctl restart docker

      - name: Show docker info
        if: always()
        shell: bash
        run: docker version ; docker info

      - name: List docker images
        if: always()
        shell: bash
        run: docker image ls --digests

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'liberica'

      - name: Checkout Spring Boot
        uses: actions/checkout@v6
        with:
          repository: spring-projects/spring-boot
          path: spring-boot

      - name: Run Spring Boot system tests
        run: |
          cd spring-boot
          ./gradlew systemTest -PtoolchainVersion=21
