name: Run Spring Boot's System Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'gradle'
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'liberica'
          cache: 'gradle'

      - name: Checkout Spring Boot
        uses: actions/checkout@v6
        with:
          repository: spring-projects/spring-boot
          path: spring-boot

      - name: Run Spring Boot system tests
        run: |
          cd spring-boot
          ./gradlew systemTest -PtoolchainVersion=21

      - name: Show docker version
        if: always()
        shell: bash
        run: docker version

      - name: List docker images
        if: always()
        shell: bash
        run: docker image ls --digests
