name: Java CI with Java 25

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'liberica'
          cache: 'grade'

      - name: Build
        run: ./gradlew build

      - name: Build image
        run: ./gradlew bootBuildImage

      - name: Show docker version
        if: always()
        shell: bash
        run: docker version

      - name: List docker images
        if: always()
        shell: bash
        run: docker image ls --digests
