name: Java CI with Java 25

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'liberica'
          cache: 'gradle'

      - name: Try and fix docker
        run: |
          if [ -f /etc/docker/daemon.json ]; then
            sudo jq '.features."containerd-snapshotter" = false' /etc/docker/daemon.json > /tmp/daemon.json
            sudo mv /tmp/daemon.json /etc/docker/daemon.json
            else
            echo '{"features": {"containerd-snapshotter": false}}' | sudo tee /etc/docker/daemon.json
          fi
          sudo systemctl restart docker          

      - name: Build
        run: ./gradlew build

      - name: Build image
        run: ./gradlew assemble bootDistZip bootBuildImage --imageName=foo --pullPolicy=IF_NOT_PRESENT

      - name: Show docker version
        if: always()
        shell: bash
        run: docker version

      - name: Show docker info
        if: always()
        shell: bash
        run: docker info

      - name: List docker images
        if: always()
        shell: bash
        run: docker image ls --digests
